### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by gerwinov** [liuhann/vue-anime#3]
Hi liuhann,

Thanks for your package, we use it for a website. Could you please remove this `console.log` statement? 

https://github.com/liuhann/vue-anime/blob/e24fb6a96cdf804a03dec3e63d03f9b17cd8bab8/src/anime-mixin.js#L82

Regards,
Gerwin

**Comment by liuhann** [comment]
Hi 
update to new version
+ vue-anime@0.2.1

thanks

**Comment by gerwinov** [comment]
One of my colleagues just updated the project and installed the new version of your package in which this has been resolved. Thanks!
