### ISSUE TITLE
Reason for update events?

### ISSUE THREAD

**Issue by gerwinov** [liuhann/vue-anime#4]
Hi liuhann,

Thanks for your package, we use it for a website. I notice a lot of `update` events are being fired per animation, why are these necessary? We have quite some animations in our project and these events seem to impact performance. The code runs fine without them too.

The events are emitted here:
https://github.com/liuhann/vue-anime/blob/e24fb6a96cdf804a03dec3e63d03f9b17cd8bab8/src/anime-mixin.js#L42
https://github.com/liuhann/vue-anime/blob/e24fb6a96cdf804a03dec3e63d03f9b17cd8bab8/src/vue-anime-timeline.js#L65

Thanks!

Regards,
Gerwin

**Comment by liuhann** [comment]
Hi

Good idea!  
vue emit events frequently would impact performance.  animejs just check the callback function exists. so there are very different

I have fixed it in new version  
+ vue-anime@0.2.2

thank you !

**Comment by gerwinov** [comment]
One of my colleagues just updated the project and installed the new version of your package in which this has been resolved. Thanks!
